#!/usr/bin/env python3
"""Generate the Mistpine AppImage icon (assets/mistpine.png) procedurally.

Deterministic, dependency-free (zlib + struct only): a stylised pine over mist on a
deep forest-green rounded square. Provenance: generated by this script, no
third-party artwork (docs/ASSETS.md).

Usage: make_icon.py [output.png] [size]
"""
import struct
import sys
import zlib


def lerp(a, b, t):
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(4))


def write_png(path, size, pixels):
    # pixels are RGBA 4-tuples (color type 6).
    raw = b""
    for y in range(size):
        raw += b"\x00"  # filter: none
        for x in range(size):
            raw += bytes(pixels[y][x])
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9))
    png += chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(png)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "mistpine.png"
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 512
    bg = (18, 34, 26, 255)        # deep forest green (RGBA)
    bg_edge = (10, 20, 15, 255)
    tree = (226, 214, 178, 255)   # pale straw (matches the in-game hat)
    trunk = (74, 52, 38, 255)
    mist = (196, 208, 200, 255)
    px = [[bg for _ in range(size)] for _ in range(size)]

    # Rounded-square background with a soft border.
    r = size * 0.18
    for y in range(size):
        for x in range(size):
            dx = max(abs(x - size / 2) - (size / 2 - r), 0)
            dy = max(abs(y - size / 2) - (size / 2 - r), 0)
            d = (dx * dx + dy * dy) ** 0.5
            if d > r:
                px[y][x] = (0, 0, 0, 0)  # transparent outside the disc
            elif d > r - size * 0.012:
                px[y][x] = bg_edge

    def disc(cx, cy, rad, col):
        for y in range(size):
            for x in range(size):
                if (x - cx) ** 2 + (y - cy) ** 2 <= rad * rad and px[y][x][3] != 0:
                    px[y][x] = col

    def tri(cx, top, half_w, h, col):
        for y in range(size):
            t = (y - top) / max(h, 1)
            if 0.0 <= t <= 1.0:
                w = half_w * t
                for x in range(size):
                    if abs(x - cx) <= w and px[y][x][3] != 0:
                        px[y][x] = col

    cx = size / 2
    # Three stacked pine tiers.
    tri(cx, size * 0.16, size * 0.30, size * 0.34, tree)
    tri(cx, size * 0.34, size * 0.36, size * 0.34, tree)
    tri(cx, size * 0.52, size * 0.40, size * 0.32, tree)
    # Trunk.
    for y in range(size):
        for x in range(size):
            if abs(x - cx) <= size * 0.035 and size * 0.80 <= y <= size * 0.88 and px[y][x][3] != 0:
                px[y][x] = trunk
    # Mist bands near the base.
    for band, (y0, alpha) in enumerate([(0.86, 0.55), (0.90, 0.40), (0.94, 0.25)]):
        for y in range(size):
            if abs(y - size * y0) < size * 0.012:
                for x in range(size):
                    if px[y][x][3] != 0:
                        px[y][x] = lerp(px[y][x], mist, alpha)
    # Two faint distant pines for depth.
    for off in (-size * 0.22, size * 0.22):
        tri(cx + off, size * 0.42, size * 0.14, size * 0.30, lerp(bg, tree, 0.35))
        tri(cx + off, size * 0.56, size * 0.17, size * 0.26, lerp(bg, tree, 0.35))

    write_png(out, size, px)
    print(f"icon written: {out} ({size}x{size})")


if __name__ == "__main__":
    main()
